[package]
name = "permissive-search"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
crossterm = "0.29"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }

must_use_candidate = "allow"
cast_possible_truncation = "allow"
